---
- name: Fedora Workstation Post Install
  hosts: localhost
  connection: local
  become: yes
  remote_user: agravelot

  roles:
    - pulseaudio
    - common
    - workstation
    - tweaks
    - dotfiles
