---
# tasks file for roles/workstation

# Additional packages
- name: "Installing additional packages"
  become_exe: sudo
  dnf:
    name:
      - git
      - flatpak
      - gimp
      - gnome-terminal-nautilus
      - gnome-tweak-tool
      - htop
      - levien-inconsolata-fonts
      - ranger
      - tmux
      - fish
      - util-linux
      - jetbrains-mono-fonts-all
      - lm_sensors
      - exfat-utils
      - fuse-exfat
#      - google-chrome-stable
    state: present

# Cleanup
- name: Remove unwanted package
  dnf:
    name:
      - open-vm-tools
      - firewalld
      - gnome-boxes
      - virtualbox-guest-additions
      - libvirt-libs
      - libvirt
    state: absent
  
# Shell
- name: Update default shell to fish
  user:
    name: agravelot
    shell: /usr/bin/fish
    append: yes

# icc brightness

- name: Installing package for icc-brightness
  dnf:
    name:
      - lcms2-devel
      - make
      - gcc
    state: present

- name: Pull icc-brightness
  git:
    repo: 'https://github.com/udifuchs/icc-brightness.git'
    dest: /tmp/icc-brightness


- name: Build the default target
  make:
    chdir: /tmp/icc-brightness

- name: Run 'install' target as root
  make:
    chdir:  /tmp/icc-brightness
    target: install
  become: yes

# Install brave

- name: Add Brave repository
  yum_repository:
    name: brave
    description: Brave RPM repository
    baseurl: https://brave-browser-rpm-release.s3.brave.com/x86_64/

- name: Importing rpm-gpg key from brave
  rpm_key:
    state: present
    key: https://brave-browser-rpm-release.s3.brave.com/brave-core.asc

- name: "Installing package for brave"
  dnf:
    name:
      brave-browser
    state: present

# Flatpak

# - name: Add the Gnome flatpak remote to the system installation
#   flatpak_remote:
#     name: gnome
#     state: present
#     flatpakrepo_url: https://sdk.gnome.org/gnome-apps.flatpakrepo

- name: Add the flathub flatpak repository remote to the user installation
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install flatpak packages
  flatpak:
    name: "{{ item }}"
    state: present
  loop:
     - com.spotify.Client
     - com.slack.Slack
     - com.discordapp.Discord
     - com.microsoft.Teams
     - com.leinardi.gst
     - com.github.calo001.fondo
     - com.getpostman.Postman
     - org.gnome.Builder
     - com.github.marktext.marktext
     - org.gabmus.hydrapaper


# SSH keys
- name: Create a 2048-bit SSH key for user agravelot in ~agravelot/.ssh/id_rsa
  user:
    name: agravelot
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa


# Docker
- name: Cleanup conflicts package with docker
  dnf:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-selinux
      - docker-engine-selinux
      - docker-engine
    state: absent

- name: Add Docker repo
  get_url:
      url: https://download.docker.com/linux/fedora/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo
  become: yes

- name: Change docker repository version to 31 unitl 33 released
  replace:
    path: /etc/yum.repos.d/docker-ce.repo
    regexp: '\$releasever'
    replace: '31'

# https://github.com/docker/for-linux/issues/955
- name: "Installing docker"
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - docker-compose
    state: present

- name: Make sure docker service is running
  systemd:
    state: started
    name: docker
    enabled: yes

- name: Add user agravelot to docker group
  user:
    name: agravelot
    groups: docker
    append: yes

# LDAC / AptX support
- name: remove previous codecs
  dnf:
    name: pulseaudio-module-bluetooth
    state: absent

- name: Add LDAC/AptX codecs
  dnf:
    name:
      - pulseaudio-module-bluetooth-freeworld
    state: present

# Intel undervolt
- name: Add LDAC/AptX codecs
  dnf:
    name:
      intel-undervolt
    state: present

- name: Make sure intel-undervolt service is running
  systemd:
    daemon_reload: true
    state: started
    name: intel-undervolt
    enabled: yes

# TODO Add config


# NodeJS
- name: Add NodeJS repository
  dnf:
    name: https://rpm.nodesource.com/pub_14.x/fc/32/x86_64/nodesource-release-fc32-1.noarch.rpm
    state: present

- name: Add Yarn repo
  get_url:
      url: https://dl.yarnpkg.com/rpm/yarn.repo
      dest: /etc/yum.repos.d/yarn.repo
  become: yes

# - name: Install Node.js and yarn
#   dnf:
#     name:
#       - nodejs
#       - gcc-c++
#       - make
#       - yarn
#     state: present

# Postgres

# - name: Install postgres
#   dnf:
#     name:
#       - postgresql-server
#       - postgresql-contrib
#       - python3-psycopg2

# - name: Init postgres
#   command:
#     cmd: postgresql-setup --initdb --unit postgresql
#     creates: /var/lib/pgsql/data

# - name: Grant users agravelot access to databases agravelot from samehost
#   postgresql_pg_hba:
#     dest: /var/lib/pgsql/data/pg_hba.conf
#     contype: host
#     method: md5
#     users: agravelot
#     source: samehost
#     create: true

# - name: Cleanup peer logins
#   postgresql_pg_hba:
#     dest: /var/lib/pgsql/data/pg_hba.conf
#     contype: local
#     method: peer
#     users: all
#     state: absent

# - name: Cleanup peer logins
#   postgresql_pg_hba:
#     dest: /var/lib/pgsql/data/pg_hba.conf
#     contype: local
#     method: peer
#     users: all
#     databases: replication
#     state: absent

# - name: Can login postgres without password (postgres bypass)
#   postgresql_pg_hba:
#     dest: /var/lib/pgsql/data/pg_hba.conf
#     contype: host
#     method: trust
#     users: postgres
#     source: samehost
#     state: present

# - name: Make sure postgresql service is running
#   systemd:
#     state: restarted
#     name: postgresql
#     enabled: no
#     daemon_reload: true

# # - name: Connect to agravelot database, create agravelot user, and grant access to database
# #   postgresql_user:
# #     db: agravelot
# #     name: agravelot
# #     password: agravelot

# - name: Remove postgres bypass
#   postgresql_pg_hba:
#     dest: /var/lib/pgsql/data/pg_hba.conf
#     contype: host
#     method: trust
#     users: postgres
#     source: samehost
#     state: absent

# - name: Make sure postgresql service is running
#   systemd:
#     state: restarted
#     name: postgresql
#     enabled: no

# Jetbrain toolbox

- name: Check if JetBrains Toolbox is already installed
  stat:
    path: /home/agravelot/.jetbrain
  register: st_jetbrains_toolbox

- block:
    - name: Get available releases
      uri:
        url: https://data.services.jetbrains.com/products/releases?code=TBA&type=release
        method: GET
      register: jetbrains_toolbox_available_releases

    - name: Get versions
      set_fact:
        jetbrains_toolbox_versions: "{{ jetbrains_toolbox_available_releases.json.TBA | map(attribute='version') | list }}"

    - name: Update version fact if latest is overridden
      set_fact:
        jetbrains_toolbox_version: "{{ jetbrains_toolbox_available_releases.json.TBA | sort(attribute='date', reverse=True) | map(attribute='version') | list | first }}"
      when: jetbrains_toolbox_version == 'latest'

    - name: Check if version is valid
      assert:
        that: (jetbrains_toolbox_version | string) in jetbrains_toolbox_versions
        msg: "The value of jetbrains_toolbox_version ({{ jetbrains_toolbox_version }}) is invalid. Available options are {{ jetbrains_toolbox_versions | join(', ') }}"

    - name: Create temporary download directory
      tempfile:
        state: directory
        suffix: ".jetbrains_toolbox_download"
      register: jetbrains_toolbox_download_dir
      changed_when: no

    - name: Download JetBrains Toolbox
      get_url:
        url: "{{ jetbrains_toolbox_available_releases.json | json_query(jetbrains_toolbox_download_query) | first }}"
        dest: "{{ jetbrains_toolbox_download_dir.path }}/jetbrains_toolbox.tar.gz"
        checksum: "sha256:{{ lookup('url', jetbrains_toolbox_available_releases.json | json_query(jetbrains_toolbox_checksum_link) | first) | regex_search('[A-Fa-f0-9]{64}') }}"
      vars:
        jetbrains_toolbox_download_query: "TBA[?version == '{{ jetbrains_toolbox_version }}'].downloads.linux.link"
        jetbrains_toolbox_checksum_link: "TBA[?version == '{{ jetbrains_toolbox_version }}'].downloads.linux.checksumLink"

    - name: Create installation folder
      file:
        path: /home/agravelot/.jetbrain
        state: directory

    - name: Unpack install archive
      unarchive:
        src: "{{ jetbrains_toolbox_download_dir.path }}/jetbrains_toolbox.tar.gz"
        dest: "/home/agravelot/.jetbrain"
        list_files: yes
        remote_src: yes
      register: jetbrains_toolbox_unarchive

    - name: Install JetBrains Toolbox
      command: "/home/agravelot/.jetbrain/{{ jetbrains_toolbox_unarchive.files | first }}/jetbrains-toolbox --install"
      become_user: agravelot
  when: st_jetbrains_toolbox.stat.exists == False
  always:
    - name: Delete temporary download directory
      file:
        path: "{{ jetbrains_toolbox_download_dir.path }}"
        state: absent
      changed_when: no

# VS Code

- name: Importing rpm-gpg key from vscode
  rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: Add Visual Studio Code repository
  yum_repository:
    name: visual-studio-code
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    enabled: true

- name: "Installing vscode"
  dnf:
    name:
      code
    state: present
    update_cache: yes

# nVidia

# PHP
- name: Install php with dependancies
  dnf:
    name:
      - php
      - composer
      - php-pecl-redis5
      - php-pecl-imagick
      - php-pgsql.x86_64

# - composer:
#     command: require
#     global_command: yes
#     arguments: hirak/prestissimo
#   become_user: agravelot

# Grub
- name: Update grub config
  command: grubby --update-kernel=ALL --args "rhgb quiet i915.enable_fbc=1 i915.enable_guc=3 modprobe.blacklist=iTCO_wdt nowatchdog systemd.unified_cgroup_hierarchy=0 mem_sleep_default=deep i915.enable_dpcd_backlight=1 mitigations=off"
  become: true

# GNOME

# needed by dconf module
- name: install psutil (Fedora)
  dnf:
    name: 
      - python3-psutil
      - dconf-editor

- name: Switch to Adwaita dark theme
  command:
    cmd: gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'

# - name: nautilus use list view
#   command:
#     cmd: gsettings set org.gnome.nautilus.preferences.default-folder-viewer "'list-view'"

# - name: nautilus use list view
#   command:
#     cmd: gsettings set org.gnome.nautilus.list-view.default-visible-columns "['name', 'size', 'date_modified', 'permissions', 'owner', 'group']"

# - name: automatic timezone
#   dconf:
#     key: "/org/gnome/desktop/datetime/automatic-timezone"
#     value: "true"

# - name: file browser shortcut
#   dconf:
#     key: "/org/gnome/settings-daemon/plugins/media-keys/home"
#     value: "'<Super>f'"

# - name: Enable nigth mode
#   command:
#     cmd: dconf write /org/gnome/settings-daemon/plugins/color/night-light-enabled true
#   become_user: agravelot

# - name: Enable nigth mode
#   dconf:
#     key: /org/gnome/settings-daemon/plugins/color/night-light-enabled
#     value: 'true'

# Multimedia codecs 
# https://docs.fedoraproject.org/en-US/quick-docs/assembly_installing-plugins-for-playing-movies-and-music/
- name: Install codecs
  dnf:
    name:
      - gstreamer1-plugins-base
      - gstreamer1-plugins-bad-free
      - gstreamer1-plugins-bad-freeworld
      - gstreamer1-plugins-bad-free-extras
      - gstreamer1-plugins-bad-free-wildmidi
      - gstreamer1-plugins-bad-free-fluidsynth
      - gstreamer1-plugins-good
      - gstreamer1-plugins-good-qt
      - gstreamer1-plugins-good-gtk
      - gstreamer1-plugins-good-extras
      - gstreamer1-plugin-openh264
      - gstreamer1-libav
      - lame

- name: Upgrade the 'Multimedia' package group
  dnf:
    state: latest
    name: '@Multimedia'
    update_only: true

# - name: Add negativo17 - Nvidia repository
#   command:
#     cmd: dnf config-manager --add-repo=https://negativo17.org/repos/fedora-nvidia.repo

- name: Install nvidia graphics driver
  dnf:
    name:
      # - vulkan
      # - nvidia-driver
      # - nvidia-driver-libs.i686
      # - nvidia-settings
      # - cuda
      # - nvidia-driver-cuda
      - libva-intel-hybrid-driver
      - libva-intel-driver
      - libva-utils

# Increase IO Notify limit

- name: set max_user_watches
  become: yes
  sysctl:
    name: fs.inotify.max_user_watches
    value: "524288"
    state: present


# Kubectl
- name: Add kubernetes repository
  yum_repository:
    name: kubernetes
    description: kubernetes repository
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    enabled: true

- name: Install kubectl
  dnf:
    name:
      - kubectl

# Custom kustomize with sops

- name: "Installing required packages"
  become_exe: sudo
  dnf:
    name:
      - go
      - make
    state: present

- name: install sops
  dnf:
    name: 'https://github.com/mozilla/sops/releases/download/v3.6.1/sops-3.6.1-1.x86_64.rpm'
    state: present
    disable_gpg_check: yes

- name: Register kustomize installation status
  command: which kustomize
  changed_when: false
  failed_when: kustomize_installed.rc not in [0,1]
  register: kustomize_installed
  become: yes
  become_user: agravelot

- name: Pull kustomize-sops
  git:
    repo: 'https://github.com/viaduct-ai/kustomize-sops.git'
    dest: /tmp/kustomize-sops
    force: yes
  become: yes
  become_user: agravelot
  when: kustomize_installed.rc not in [ 0 ]

- name: Remove kustomize version call in build script
  replace:
    path: /tmp/kustomize-sops/scripts/install-kustomize.sh
    regexp: 'kustomize version'
    replace: ''
  become: yes
  become_user: agravelot
  when: kustomize_installed.rc not in [ 0 ]

- name: Execute the command in remote shell; stdout goes to the specified file on the remote.
  shell: export XDG_CONFIG_HOME=/home/agravelot/.config
  become: yes
  become_user: agravelot
  when: kustomize_installed.rc not in [ 0 ]

# - name: Patch go.mod to avoid domain name nout found
#   shell: echo 'replace vbom.ml/util => github.com/fvbommel/sortorder v1.0.1' >> /tmp/kustomize-sops/go.mod
#   become: yes
#   become_user: agravelot
#   when: kustomize_installed.rc not in [ 0 ]

- name: Build the default target
  shell:
    cmd: XDG_CONFIG_HOME=/home/agravelot/.config GOPATH=/home/agravelot/.go make
    chdir: /tmp/kustomize-sops
  become: yes
  become_user: agravelot
  when: kustomize_installed.rc not in [ 0 ]

- name: Install Kustomize
  shell:
    chdir: /tmp/kustomize-sops
    cmd: XDG_CONFIG_HOME=/home/agravelot/.config GOPATH=/home/agravelot/.go make kustomize
  become: yes
  become_user: agravelot
  when: kustomize_installed.rc not in [ 0 ]

- name: Install KSOPS plugin
  shell:
    chdir: /tmp/kustomize-sops
    cmd: XDG_CONFIG_HOME=/home/agravelot/.config GOPATH=/home/agravelot/.go make install
  become: yes
  become_user: agravelot
  when: kustomize_installed.rc not in [ 0 ]

# Theme bigsur

- name: Install GTK2 engines requirements
  dnf:
    name:
      - gtk-murrine-engine 
      - gtk2-engines

- name: Installation Depends requirement
  dnf:
    name:
      - sassc
      - optipng
      - inkscape
      - glib2-devel

- name: Pull WhiteSur-gtk-theme
  git:
    repo: 'https://github.com/vinceliuice/WhiteSur-gtk-theme.git'
    dest: /tmp/WhiteSur-gtk-theme

- name: Install WhiteSur-gtk-theme
  shell:
    chdir: /tmp/WhiteSur-gtk-theme
    cmd: ./install.sh -g
  become: yes
  become_user: agravelot

- name: Pull WhiteSur-icon-theme
  git:
    repo: 'https://github.com/vinceliuice/WhiteSur-icon-theme.git'
    dest: /tmp/WhiteSur-icon-theme

- name: Install WhiteSur-icon-theme
  shell:
    chdir: /tmp/WhiteSur-icon-theme
    cmd: ./install.sh
  become: yes
  become_user: agravelot

# - name: Override flatpak themes with local
#   shell:
#     chdir: /tmp/WhiteSur-icon-theme
#     cmd: flatpak override --filesystem=~/.themes
#   become: yes
#   become_user: agravelot
  


- name: Installation Depends requirement
  dnf:
    name:
      - libX11-devel
      - libXcursor-devel
      - libpng-devel

- name: Creates directory
  file:
    path: ~/.icons/
    state: directory
  become: yes
  become_user: agravelot

- name: Install cursor pack
  unarchive:
    src: https://github.com/ful1e5/apple_cursor/releases/download/v1.0.6/macOSBigSur.tar.gz
    dest: ~/.icons/
    remote_src: yes
  become: yes
  become_user: agravelot